- hosts: cassandra:children
  tasks:
    - name: Check Cassandra service status
      service:
        name: cassandra
        state: started
      register: cassandra_status
      
    - name: Print Cassandra service status
      debug:
        msg: "Cassandra Service Status: {{ cassandra_status.state }}"
