---
- name: Remove course-metrics service
  shell: "docker service rm course-metrics"
  ignore_errors: yes

- name: Deploy course-metrics service
  shell: "docker service create --with-registry-auth --replicas {{ lms_service_replicas }} -p 9000:9000  --name course-metrics --hostname course-metrics --reserve-memory {{ lms_service_reservation_memory }} --limit-memory {{ lms_service_limit_memory }} --limit-cpu {{ lms_service_limit_cpu }} --reserve-cpu {{ lms_service_reservation_cpu }} --health-cmd 'wget -qO- lms-service:9000/service/health || exit 1' --health-timeout 10s --health-retries 5  --network application_default --env JAVA_OPTIONS={{ lms_java_mem_limit }} --env-file /home/deployer/env/course-metrics.env  {{hub_org}}/{{image_name}}:{{image_tag}}"
  args:
    chdir: /home/deployer/stack
