---
- name: Retrieve Cassandra backup log
  hosts: cassandra
  gather_facts: no
  tasks:
    - name: Get yesterday's date in YYYY/MM/DD format
      command: date -d "yesterday" +'%Y/%m/%d'
      register: yesterday_date_yyyy_mm_dd

    - name: Check for 100% success in Cassandra backup log for yesterday's date
      shell:
        cmd: grep "{{ yesterday_date_yyyy_mm_dd.stdout }}" /var/log/cassandra/backup.log | grep -E '100%'
      register: cassandra_backup_status_yesterday

    - name: Display the results of the grep command
      debug:
        msg: "{{ cassandra_backup_status_yesterday.stdout }}"

    # Add additional tasks or error handling as needed
