---
- name: Execute bash script with sudo and print output
  hosts: localhost  # You can change this to the target host(s) where the script is located
  become: yes  # Run tasks with sudo privileges
  tasks:
    - name: Run the bash script and capture output
      command: "/opt/scripts/certificate_count.sh"
      register: script_output
      timeout: 180  # Timeout set to 180 seconds (3 minutes)
      changed_when: false  # Since the script doesn't modify anything, marking it as unchanged

    - name: Print script output to console
      debug:
        var: script_output.stdout_lines
