---
- name: Execute bash script with sudo and print output
  hosts: localhost  # You can change this to the target host(s) where the script is located
  become: yes  # Run tasks with sudo privileges
  tasks:
    - name: Run the bash script and capture output
      shell: "cd /opt/scripts && ./certificate_count.sh"  # Change to the correct path
      register: script_output
      async: 180  # Set a timeout of 180 seconds (3 minutes)
      poll: 0  # Check every second until the async task completes

    - name: Print script output to console
      debug:
        msg: "{{ script_output.stdout }}"
