---
- name: Execute certificate_count.sh and print output in Jenkins
  hosts: localhost  # You can change this to the target host(s) where the script is located
  become: yes  # Run tasks with sudo privileges
  tasks:
    - name: Run certificate_count.sh and capture output
      shell: "/opt/scripts/certificate_count.sh"
      register: script_output
      args:
        warn: false  # Suppress warnings in the output

    - name: Print script output to Jenkins console
      debug:
        msg: "{{ script_output.stdout }}"
