---
- name: Execute the certificate_count.sh and Print Output
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Set Execute Permissions on Shell Script
      file:
        path: /opt/scripts/certificate_count.sh
        mode: "+x"

    - name: Execute Shell Script
      command: /opt/scripts/certificate_count.sh
      register: script_output

    - name: Print Script Output
      debug:
        msg: "{{ script_output.stdout }}"
