---
- name: Execute the certificate_count.sh and Print Output
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Set Execute Permissions on Shell Script
      file:
        path: /opt/scripts/certificate_count.sh
        mode: "+x"

    - name: Execute Shell Script
      shell: /opt/scripts/certificate_count.sh
      args:
        executable: /bin/bash
      register: script_output
      changed_when: false

    - name: Print Script Output
      debug:
        msg: |
          Certificate Counts for {{ ansible_date_time.date }}
          {{ script_output.stdout }}
          {{ script_output.stderr }}
