---
- name: Run certificate count script
  hosts: localhost
  gather_facts: false
  vars:
    script_path: "/opt/scripts/certificate_count.sh"

  tasks:
    - name: Execute the bash script and capture output
      shell: "{{ script_path }}"
      register: script_output
      ignore_errors: yes  # Ignore errors if the script exits with a non-zero status

    - name: Print output in Jenkins console
      debug:
        msg: |
          Certificate Counts
          ╔══════════════╦═════════════════╦═════════╗
          ║ Date         ║ Time Range      ║ Count   ║
          ╠══════════════╬═════════════════╬═════════╣
          {{ script_output.stdout | regex_replace('(\\|)+', '\\|') | regex_replace('^\\s+|\\s+$', '', 'g') | regex_replace('\\s+\\|\\s+', '║') | regex_replace('^', '║') | regex_replace('$', '║') }}
          ╚══════════════╩═════════════════╩═════════╝
