---
- name: Check disk space on mongo_master
  hosts: mongo_master
  gather_facts: no

  tasks:
    - name: Check mongo disk space
      command: df -h
      register: mongo_disk_space

    - name: Print mongo disk space
      debug:
        msg: "mongo disk space: {{ mongo_disk_space.stdout }}"

- name: Check disk space on postgres
  hosts: postgresql-master-1
  gather_facts: no

  tasks:
    - name: Check postgres disk space
      command: df -h
      register: postgres_disk_space

    - name: Print spark disk space
      debug:
        msg: "postgres disk space: {{ postgres_disk_space.stdout }}"


- name: Check disk space on spark01
  hosts: dp-spark-ps
  gather_facts: no

  tasks:
    - name: Check spark01 disk space
      command: df -h
      register: spark_disk_space

    - name: Print spark disk space
      debug:
        msg: "spark disk space: {{ spark_disk_space.stdout_lines }}" 
        
- name: Check disk space on redis
  hosts: redis
  gather_facts: no
        
  tasks:
    - name: Check redis disk space
      command: df -h
      register: redis_disk_space

    - name: Print redis disk space
      debug:
        msg: "redis disk space: {{ redis_disk_space.stdout_lines }}" 
        
- name: Check disk space on keycloak-1 
  hosts: keycloak-1
  gather_facts: no
        
  tasks:
    - name: Check keycloak disk space
      command: df -h
      register: keycloak_disk_space

    - name: Print keycloak disk space
      debug:
        msg: "keycloak disk space: {{ keycloak_disk_space.stdout_lines }}" 
        
- name: Check disk space on learning1 
  hosts: learning1
  gather_facts: no
        
  tasks:
    - name: Check learning1 disk space
      command: df -h
      register: learning1_disk_space

    - name: Print learning1 disk space
      debug:
        msg: "learning1 disk space: {{ learning1_disk_space.stdout_lines }}" 
        
- name: Check disk space on ml-analytics-service
  hosts: ml-analytics-service
  gather_facts: no
        
  tasks:
    - name: Check ml-analytics-service disk space
      command: df -h
      register: ml-analytics-service_disk_space

    - name: Print ml-analytics-service disk space
      debug:
        msg: "ml-analytics-service disk space: {{ ml-analytics-service_disk_space.stdout_lines }}"        

- name: Check disk space on cassandra
  hosts: cassandra-01
  gather_facts: no
        
  tasks:
    - name: Check cassandra disk space
      command: df -h
      register:cassandra_disk_space
      
    - name: Print cassandra disk space
      debug:
        msg: "cassandra disk space: {{ cassandra_disk_space.stdout_lines }}" 

        
        
