---
- name: Check Running and Non-Running Pods
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get list of pods
      shell: kubectl get pods --all-namespaces
      register: pods_output

    - name: Format Running Pods Output
      debug:
        msg: "{{ item.split() | join('\t') }}"
      loop: "{{ pods_output.stdout_lines }}"
      when: "'Running' in item"

    - name: Format Non-Running Pods Output
      debug:
        msg: "{{ item.split() | join('\t') }}"
      loop: "{{ pods_output.stdout_lines }}"
      when: "'Running' not in item"
