---
- name: Execute certcheck.py and Print Output
  hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Set Execute Permissions on Python Script
      command: chmod +x /opt/scripts/certcheck.py

    - name: Execute Python Script
      command: python3 /opt/scripts/certcheck.py
      register: script_output

    - name: Print Script Output
      debug:
        msg: "{{ script_output.stdout }}"
