---
- name: Check Pod Status in All Namespaces
  hosts: localhost
  gather_facts: no
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  tasks:
    - name: Check Running Pods in Namespaces
      shell: kubectl get pods -A --field-selector=status.phase=Running -o custom-columns=NAMESPACE:.metadata.namespace,NAME:.metadata.name,READY://:.status.containerStatuses[0].ready,STATUS:.status.phase,RESTARTS:.status.containerStatuses[0].restartCount,AGE:.metadata.creationTimestamp
      register: running_pods
      changed_when: false
      failed_when: false

    - name: Print Running Pods
      debug:
        msg: |
          NAMESPACE     NAME                                     READY   STATUS    RESTARTS   AGE
          {% for line in running_pods.stdout_lines[1:] %}
          {{ line.split()[0] }}     {{ line.split()[1] }}     {{ line.split()[2] if line.split()[2] != "<none>" else "" }}     {{ line.split()[3] }}     {{ line.split()[4] }}     {{ ((ansible_date_time.epoch|int - line.split()[-1][:-1].replace('T',' ') | to_datetime).days) }}d
          {% endfor %}
      when: running_pods.stdout_lines | length > 1

    - name: Check Non-Running Pods in Namespaces
      shell: kubectl get pods -A --field-selector=status.phase!=Running -o custom-columns=NAMESPACE:.metadata.namespace,NAME:.metadata.name,READY://:.status.containerStatuses[0].ready,STATUS:.status.phase,RESTARTS:.status.containerStatuses[0].restartCount,AGE:.metadata.creationTimestamp
      register: non_running_pods
      changed_when: false
      failed_when: false

    - name: Print Non-Running Pods
      debug:
        msg: |
          NAMESPACE     NAME                                     READY   STATUS    RESTARTS   AGE
          {% for line in non_running_pods.stdout_lines[1:] %}
          {{ line.split()[0] }}     {{ line.split()[1] }}     {{ line.split()[2] if line.split()[2] != "<none>" else "" }}     {{ line.split()[3] }}     {{ line.split()[4] }}     {{ ((ansible_date_time.epoch|int - line.split()[-1][:-1].replace('T',' ') | to_datetime).days) }}d
          {% endfor %}
      when: non_running_pods.stdout_lines | length > 1
