- name: Check Pod Status in All Namespaces
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Define ansible_date_time
      set_fact:
        ansible_date_time:
          epoch: "{{ ansible_date_time.epoch }}"
          date: "{{ ansible_date_time.date }}"
          time: "{{ ansible_date_time.time }}"

    - name: Check Running Pods in Namespaces
      shell: |
        kubectl get pods -A --field-selector=status.phase=Running -o custom-columns=NAMESPACE:.metadata.namespace,NAME:.metadata.name,READY:.status.replicas,STATUS:.status.phase,RESTARTS:.status.containerStatuses[0].restartCount,AGE:.metadata.creationTimestamp --no-headers | sort | uniq
      register: running_pods
      changed_when: false
      failed_when: false

    - name: Print Running Pods
      debug:
        msg: |
          NAMESPACE     NAME                                     READY   STATUS    RESTARTS   AGE
          {% for line in running_pods.stdout_lines %}
          {{ line.split()[0] }}     {{ line.split()[1] }}     {{ line.split()[2] if line.split()[2] != "<none>" else "0" }}/{{ line.split()[2] if line.split()[2] != "<none>" else "0" }}   {{ line.split()[3] }}     {{ line.split()[4] }}          {{ ((ansible_date_time.epoch|int - line.split()[-1] | to_datetime).days | default(0)) }} days ago
          {% endfor %}
      when: running_pods.stdout_lines | length > 0

    - name: Check Non-Running Pods in Namespaces
      shell: |
        kubectl get pods -A --field-selector=status.phase!=Running -o custom-columns=NAMESPACE:.metadata.namespace,NAME:.metadata.name,READY:.status.replicas,STATUS:.status.phase,RESTARTS:.status.containerStatuses[0].restartCount,AGE:.metadata.creationTimestamp --no-headers | sort | uniq
      register: non_running_pods
      changed_when: false
      failed_when: false

    - name: Print Non-Running Pods
      debug:
        msg: |
          NAMESPACE     NAME                                     READY   STATUS    RESTARTS   AGE
          {% for line in non_running_pods.stdout_lines %}
          {{ line.split()[0] }}     {{ line.split()[1] }}     {{ line.split()[2] if line.split()[2] != "<none>" else "0" }}/{{ line.split()[2] if line.split()[2] != "<none>" else "0" }}   {{ line.split()[3] }}     {{ line.split()[4] }}          {{ ((ansible_date_time.epoch|int - line.split()[-1] | to_datetime).days | default(0)) }} days ago
          {% endfor %}
      when: non_running_pods.stdout_lines | length > 0
