---
- name: Check Pod Status in All Namespaces
  hosts: localhost
  gather_facts: no
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  tasks:
    - name: Get all namespaces
      shell: kubectl get ns -o jsonpath='{.items[*].metadata.name}'
      register: namespaces_output
      changed_when: false

    - name: Loop through each namespace
      set_fact:
        all_namespaces: "{{ namespaces_output.stdout.split() }}"
      loop: "{{ all_namespaces }}"
      register: loop_result

    - name: Check Pods in each namespace
      shell: kubectl get pods -n {{ item }} --no-headers=true
      loop: "{{ all_namespaces }}"
      register: pods_by_namespace
      changed_when: false
      failed_when: pods_by_namespace.rc != 0  # Adding error handling

    - name: Print Pods with specified statuses in each namespace
      debug:
        msg: |
          Namespace: {{ item.item }}
          {% for pod in item.stdout_lines %}
          - {{ pod.split()[0] }}: {{ pod.split()[2] }} ({{ pod.split()[1] }})
          {% endfor %}
      loop: "{{ pods_by_namespace.results }}"
      vars:
        regex: "(CrashLoopBackOff|ContainerStatusUnknown|Error|Unknown|Running)"
      when: item.stdout_lines | select('match', regex) | list | length > 0
