---
- name: Check disk space on mongo_master
  hosts: mongo_master
  gather_facts: no
  tasks:
    - name: Check mongo disk space
      shell: df -h | awk 'BEGIN {print "Filesystem  Size  Used  Avail  Use%  Mounted  on"} /Filesystem|\/dev\/sda1\s/ && $5+0 > 75' | column -t
      register: mongo_disk_space
      changed_when: false

    - name: Print mongo disk space
      debug:
        msg: "{{ mongo_disk_space.stdout }}"
      ##when: mongo_disk_space.stdout_lines[1].split()[4] | int > 75

- name: Check disk space on postgres
  hosts: postgresql-master-1
  gather_facts: no
  tasks:
    - name: Check postgres disk space
      shell: df -h | awk 'BEGIN {print "Filesystem  Size  Used  Avail  Use%  Mounted  on"} /Filesystem|\/dev\/sda1\s/ && $5+0 > 75' | column -t
      register: postgres_disk_space
      changed_when: false

    - name: Print spark disk space
      debug:
        msg: "{{ postgres_disk_space.stdout }}"
      ##when: postgres_disk_space.stdout_lines[1].split()[4] | int > 75

- name: Check disk space on spark-sl
  hosts: py-spark-sl
  gather_facts: no
  tasks:
    - name: Check spark-sl disk space
      shell: df -h | awk 'BEGIN {print "Filesystem  Size  Used  Avail  Use%  Mounted  on"} /Filesystem|\/dev\/sda1\s/ && $5+0 > 75' | column -t
      register: sparksl_disk_space
      changed_when: false

    - name: Print spark disk space
      debug:
        msg: "{{ sparksl_disk_space.stdout }}"
      ##when: sparksl_disk_space.stdout_lines[1].split()[4] | int > 75

- name: Check disk space on redis
  hosts: redis
  gather_facts: no
  tasks:
    - name: Check redis disk space
      shell: df -h | awk 'BEGIN {print "Filesystem  Size  Used  Avail  Use%  Mounted  on"} /Filesystem|\/dev\/sda1\s/ && $5+0 > 75' | column -t
      register: redis_disk_space
      changed_when: false

    - name: Print redis disk space
      debug:
        msg: "{{ redis_disk_space.stdout }}"
      ##when: redis_disk_space.stdout_lines[1].split()[4] | int > 75

- name: Check disk space on keycloak-1
  hosts: keycloak-1
  gather_facts: no
  tasks:
    - name: Check keycloak disk space
      shell:  df -h | awk 'BEGIN {print "Filesystem  Size  Used  Avail  Use%  Mounted  on"} /Filesystem|\/dev\/sda1\s/ && $5+0 > 75' | column -t
      register: keycloak_disk_space
      changed_when: false

    - name: Print keycloak disk space
      debug:
        msg: "{{ keycloak_disk_space.stdout }}"
##when: keycloak_disk_space.stdout_lines[1].split()[4] | int > 75

- name: Check disk space on learning1
  hosts: learning1
  gather_facts: no
  tasks:
    - name: Check learning1 disk space
      shell: df -h | awk 'BEGIN {print "Filesystem  Size  Used  Avail  Use%  Mounted  on"} /Filesystem|\/dev\/sda1\s/ && $5+0 > 75' | column -t
      register: learning1_disk_space
      changed_when: false

    - name: Print learning1 disk space
      debug:
        msg: "{{ learning1_disk_space.stdout }}"
      ##when: learning1_disk_space.stdout_lines[1].split()[4] | int > 75

- name: Check disk space on influxdb
  hosts: dp-influx-ps
  gather_facts: no
  tasks:
    - name: Check influxdb disk space
      shell: df -h | awk 'BEGIN {print "Filesystem  Size  Used  Avail  Use%  Mounted  on"} /Filesystem|\/dev\/sda1\s/ && $5+0 > 75' | column -t
      register: influxdb_disk_space
      changed_when: false

    - name: Print influxdb disk space
      debug:
        msg: "{{ influxdb_disk_space.stdout }}"
      ##when: influxdb_disk_space.stdout_lines[1].split()[4] | int > 75

- name: Check disk space on dp-cassandra
  hosts: dp-cassandra
  gather_facts: no
  tasks:
    - name: Check cassandra disk space
      shell: df -h | awk 'BEGIN {print "Filesystem  Size  Used  Avail  Use%  Mounted  on"} /Filesystem|\/dev\/sda1\s/ && $5+0 > 75' | column -t
      register: cassandra_disk_space
      changed_when: false

    - name: Print cassandra disk space
      debug:
        msg: "{{ cassandra_disk_space.stdout }}"
      ##when: cassandra_disk_space.stdout_lines[1].split()[4] | int > 75
