---
- name: Check Pod Status in All Namespaces
  hosts: localhost
  gather_facts: no
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  tasks:
    - name: Get Pod Status in All Namespaces
      shell: kubectl get pods -A
      register: pod_status
      changed_when: false
      failed_when: false

    - name: Parse Pod Status
      set_fact:
        pod_status_lines: "{{ pod_status.stdout_lines }}"
      when: pod_status.stdout_lines | length > 0

    - name: Print Pod Status
      debug:
        msg: "{{ pod_status_lines | join('\n') }}"
      when: pod_status_lines is defined
