- name: Check Service Status
  hosts: all
  gather_facts: yes

  tasks:
    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Print service status
      debug:
        msg: "{{ item.key }} Service Status: {{ 'running' if ansible_services[item.key]['state'] == 'running' else 'not running' }}"
      loop: "{{ ansible_services.items() }}"
      when: item.key in [
        'keycloak',
        'cassandra',
        'neo4j',
        'elasticsearch',
        'redis',
        'kafka',
        'tomcat',
        'influxdb',
        'postgresql',
        'survey-sl-mongodb',
        'processing-cluster-kafka-1',
        'flink-processing-cluster-kafka'
      ]
