---
- name: Execute certcheck.py and Print Output
  hosts: jenkins-master
  gather_facts: no

  tasks:
    - name: Execute Python Script
      command: python3 /root/certcheck.py
      register: script_output

    - name: Print Script Output
      debug:
        msg: "{{ script_output.stdout }}"
