---
- name: Check Pod Status in All Namespaces
  hosts: localhost
  gather_facts: no
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  tasks:
    - name: Check Running Pods in Namespaces
      shell: kubectl get pods -A --field-selector=status.phase=Running -o custom-columns=NAME:.metadata.name,READY:.status.containerStatuses[0].ready,STATUS:.status.phase,RESTARTS:.status.containerStatuses[0].restartCount,.metadata.creationTimestamp --no-headers
      register: running_pods
      changed_when: false
      failed_when: false

    - name: Calculate Age
      set_fact:
        running_pods_with_age: "{{ running_pods.stdout_lines | map('regex_replace', '^(\\S+)\\s+(\\S+)\\s+(\\S+)\\s+(\\S+)\\s+(.*)$', {'name': '\\1', 'ready': '\\2', 'status': '\\3', 'restarts': '\\4', 'age': ((now() - \\5 | to_datetime).days | int) | string}) | list }}"

    - name: Print Running Pods
      debug:
        msg: |
          NAME                                     READY   STATUS    RESTARTS      AGE
          {% for pod in running_pods_with_age %}
          {{ pod.name }}     {{ pod.ready }}     {{ pod.status }}   {{ pod.restarts }}             {{ pod.age }}d
          {% endfor %}
      when: running_pods.stdout_lines | length > 0
