---
- name: Check SSL certificate expiry dates
  hosts: localhost
  tasks:
    - name: Fetch SSL certificate information
      uri:
        url: "https://{{ item }}"
        return_content: yes
        status_code:
          - 200
          - 201  # Add other status codes you want to treat as successful
        register: certificate_info
      ignore_errors: yes  # Ignore all errors, including non-200 status codes
      with_items:
        - ops.diksha.gov.in
        - api.diksha.gov.in
        - diksha.gov.in
        - vdn.diksha.gov.in
        - merge.diksha.gov.in
        - obj.diksha.gov.in
        - obj.vdn.diksha.gov.in
        - static.diksha.gov.in
        - oci.diksha.gov.in
        - myaccess.diksha.orcl.cloud/login
        - files.odev.oci.diksha.gov.in
        - vdn.oci.diksha.gov.in
        - dev.oci.diksha.gov.in
        - support.diksha.gov.in
        - teachersupport.diksha.gov.in
        - vsk.ndear.gov.in
        - sskvsk.karnataka.gov.in
        - vsk.schooleducationharyana.gov.in
        - pp-myjp.diksha.gov.in
        - ejaaduipitara.ncert.gov.in.

    - name: Extract SSL certificate expiry date and days left
      set_fact:
        expiry_date: "{{ (item.content | regex_findall('(not valid after|expiry date|expire date|expires on|expire on)(.*)\n', '\\2') | first).split('(')[0] }}"
        days_left: "{{ ((expiry_date | to_datetime(format='%b %d %H:%M:%S %Y %Z')) - (ansible_date_time.iso8601 | to_datetime)).days }}"
        status_code: "{{ item.status }}"
        success: "{{ item.status == 200 }}"
      with_items: "{{ certificate_info.results | default([]) }}"
      when: certificate_info is defined and certificate_info.results | length > 0

    - name: Display SSL certificate expiry dates
      debug:
        msg: "{{ item.item }} - Status Code: {{ item.status_code }} | Expiry Date: {{ item.expiry_date }} ({{ item.days_left }} days left)"
      with_items: "{{ certificate_info.results | default([]) }}"
      when: item.success | default(true)
