---
- name: Check disk space on mongo_master
  hosts: mongo_master
  gather_facts: no

  tasks:
    - name: Check mongo disk space
      command: df -h
      register: mongo_disk_space

    - name: Print mongo disk space
      debug:
        msg: "mongo disk space: {{ mongo_disk_space.stdout_lines }}"

