---
- name: Check Pod Status in All Namespaces
  hosts: localhost
  gather_facts: no
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  tasks:
    - name: Check Running Pods in Namespaces
      shell: kubectl get pods -A --field-selector=status.phase=Running -o custom-columns=NAME:.metadata.name,READY:.status.containerStatuses[0].ready,STATUS:.status.phase,RESTARTS:.status.containerStatuses[0].restartCount,AGE:{{ 'now' | to_date }}-{{ '.metadata.creationTimestamp' | from_date }} --no-headers
      register: running_pods
      changed_when: false
      failed_when: false

    - name: Print Running Pods
      debug:
        msg: |
          NAME                                     READY   STATUS    RESTARTS      AGE
          {% for line in running_pods.stdout_lines %}
          {{ line.split()[0] }}     {{ line.split()[1] }}/{{ line.split()[1] }}     {{ line.split()[2] }}   {{ line.split()[3] }}             {{ line.split()[4] }}
          {% endfor %}
      when: running_pods.stdout_lines | length > 0

    - name: Check Non-Running Pods in Namespaces
      shell: kubectl get pods -A --field-selector=status.phase!=Running -o custom-columns=NAME:.metadata.name,READY:.status.containerStatuses[0].ready,STATUS:.status.phase,RESTARTS:.status.containerStatuses[0].restartCount,AGE:{{ 'now' | to_date }}-{{ '.metadata.creationTimestamp' | from_date }} --no-headers
      register: non_running_pods
      changed_when: false
      failed_when: false

    - name: Print Non-Running Pods
      debug:
        msg: |
          NAME                                     READY   STATUS    RESTARTS      AGE
          {% for line in non_running_pods.stdout_lines %}
          {{ line.split()[0] }}     {{ line.split()[1] }}/{{ line.split()[1] }}     {{ line.split()[2] }}   {{ line.split()[3] }}             {{ line.split()[4] }}
          {% endfor %}
      when: non_running_pods.stdout_lines | length > 0
