---
- name: Check Pod Status in All Namespaces
  hosts: localhost
  gather_facts: no
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  tasks:
    - name: Get Pod Statuses
      shell: kubectl get pods --all-namespaces --field-selector=status.phase!=Running,status.phase!=Succeeded --field-selector='status.containerStatuses[*].state.waiting.reason!=PodInitializing'
      register: pod_status
      changed_when: false
      failed_when: false

    - name: Parse Pod Statuses
      set_fact:
        pod_lines: "{{ pod_status.stdout_lines }}"
      when: pod_status.stdout_lines | length > 0

    - name: Print Pod Statuses
      debug:
        msg: "{{ pod_lines | join('\n') }}"
      when: pod_lines is defined
