- hosts: druid
  tasks:
    - name: Gather service facts
      service_facts:

    - name: Print Druid service status using service facts
      debug:
        msg: "Druid Service Status: {{ ansible_facts.services['druid'].state }}"
