- name: Fetch Druid data source information
  hosts: druid
  gather_facts: no
  tasks:
    - name: Get Druid data source details
      k8s_info:
        api_version: v1
        kind: Pod
        namespace: your_namespace
        label_selectors:
          app: druid
      register: druid_pods

    - name: Extract Druid data source information
      set_fact:
        druid_data_sources: "{{ druid_data_sources | default([]) + [{
          'name': item.metadata.name,
          'namespace': item.metadata.namespace
        }] }}"
      loop: "{{ druid_pods.resources }}"
      loop_control:
        loop_var: item

    - name: Get Druid data source name, endpoint, pod, service, and availability
      shell: |
        druid_data_source_name=$(curl -s http://localhost:8888/druid/indexer/v1/datasources)
        druid_endpoint=$(kubectl get svc -n {{ item.metadata.namespace }} | grep 'druid-broker' | awk '{print $4}')
        druid_pod="{{ item.metadata.name }}"
        druid_service=$(kubectl get svc -n {{ item.metadata.namespace }} | grep 'druid-broker' | awk '{print $1}')
        druid_availability=$(kubectl get pod -n {{ item.metadata.namespace }} {{ item.metadata.name }} -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}')
        echo "Druid Data Source Name: $druid_data_source_name"
        echo "Druid Endpoint: $druid_endpoint"
        echo "Namespace: {{ item.metadata.namespace }}"
        echo "Pod: {{ item.metadata.name }}"
        echo "Service: $druid_service"
        echo "Availability: $druid_availability"
      loop: "{{ druid_pods.resources }}"
      loop_control:
        loop_var: item
