- hosts: sl-druid
  tasks:
    - name: Gather service facts
      service_facts:

    - name: Print Druid service status
      debug:
        msg: "Druid Service Status: {{ ansible_facts.services['druid'].state }}"
