- name: Fetch Druid data source information
  hosts: druid
  gather_facts: no
  tasks:
    - name: Get Druid data source details
      k8s_info:
        api_version: v1
        kind: Pod
        namespace: your_namespace
        label_selectors:
          app: druid
      register: druid_pods

    - name: Extract Druid data source information
      set_fact:
        druid_data_sources: []
      loop: "{{ druid_pods.resources }}"
      loop_control:
        loop_var: pod_info
      vars:
        pod_name: "{{ pod_info.metadata.name }}"
        pod_namespace: "{{ pod_info.metadata.namespace }}"
      tasks:
        - name: Get Druid data source name, endpoint, namespace, pod, service, and availability
          shell: |
            druid_data_source_name=$(curl -s http://localhost:8888/druid/indexer/v1/datasources)
            druid_endpoint=$(kubectl get svc -n {{ pod_namespace }} | grep 'druid-broker' | awk '{print $4}')
            druid_namespace="{{ pod_namespace }}"
            druid_pod="{{ pod_name }}"
            druid_service=$(kubectl get svc -n {{ pod_namespace }} | grep 'druid-broker' | awk '{print $1}')
            druid_availability=$(kubectl get pod -n {{ pod_namespace }} {{ pod_name }} -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}')
            echo "Druid Data Source Name: $druid_data_source_name"
            echo "Druid Endpoint: $druid_endpoint"
            echo "Namespace: $druid_namespace"
            echo "Pod: $druid_pod"
            echo "Service: $druid_service"
            echo "Availability: $druid_availability"
          register: druid_info

        - name: Add Druid data source information to the list
          set_fact:
            druid_data_sources: "{{ druid_data_sources + [{
              'name': druid_info.stdout_lines[0],
              'endpoint': druid_info.stdout_lines[1],
              'namespace': druid_info.stdout_lines[2],
              'pod': druid_info.stdout_lines[3],
              'service': druid_info.stdout_lines[4],
              'availability': druid_info.stdout_lines[5]
            }] }}"
