---
- name: Display Kafka consumer group status in table format
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Loop through Kafka consumer groups and check lag status
      shell: /opt/kafka/bin/kafka-consumer-groups.sh --bootstrap-server "localhost:9092" --describe --group "{{ item }}"
      register: consumer_group_output
      loop:
        - "dev-audit-event-generator-group"
        - "telemetry-group"
        - "prometheus-metrics-consumer"
        - "dev-post-publish-processor-group"
        - "ml-project-service"
        - "dev-audit-history-indexer-group"
        - "learning-127.0.1.1"
        - "dev-search-indexer-group"
        - "outbound"
        - "dev-enrolment-reconciliation-group"
        - "devsamiksha"
        - "dev-relation-cache-updater-group"
        - "dev-content-publish-group"
        - "dev-qrcode-image-generator-group"
      loop_control:
        label: "{{ item }}"
        
    - name: Install tabulate Python library
      pip:
        name: tabulate
        
    - name: Format Kafka consumer group status into table format
      run_once: true
      script: |
        from tabulate import tabulate
        output_data = []
        for item in consumer_group_output.results:
            group_name = item.item
            status = item.stdout
            lag = int(status.split('LAG')[1].split()[0]) if 'LAG' in status else None
            lag_status = 'Normal' if lag is not None and lag <= 9 else 'High' if lag is not None and lag > 9 else 'Unknown'
            output_data.append([group_name, lag, lag_status])
        
        table = tabulate(output_data, headers=["Consumer Group", "Kafka Lag", "Lag Status"], tablefmt="pipe")
        print(table)
