- name: Display Kafka consumer group status
  hosts: ingestion-cluster-kafka
  gather_facts: no
  tasks:
    - name: Loop through Kafka consumer groups and check lag status
      shell: /opt/kafka/bin/kafka-consumer-groups.sh --bootstrap-server "localhost:9092" --describe --group "{{ item }}"
      register: consumer_group_output
      loop:
        - "jobmanager"
        - "dev-audit-event-generator-group"
        - "telemetry-group"
        - "prometheus-metrics-consumer"
        - "create-entity-consumer-group"
        - "ml-project-service"
        - "dev-audit-history-indexer-group"
        - "learning-127.0.1.1"
        - "dev-search-indexer-group"
        - "outbound"
        - "dev-enrolment-reconciliation-group"
        - "devsamiksha"
        - "dev-relation-cache-updater-group"
        - "dev-content-publish-group"
        - "dev-qrcode-image-generator-group"
      loop_control:
        label: "{{ item }}"

    - name: Print formatted Kafka lag status
      debug:
        msg: |
          {% for result in consumer_group_output.results %}
          {% set output_lines = result.stdout_lines %}
          {% for line in output_lines[2:] %}
          {% set values = line.split() %}
          | Group: {{ values[0] }}
          | Topic: {{ values[1] }}
          | Partition: {{ values[2] }}
          | Current-OFFSET: {{ values[3] }}
          | LOG-END-OFFSET: {{ values[4] }}
          | LAG: {{ values[5] }}
          | CONSUMER-ID: {{ values[6] }}
          | HOST: {{ values[7] }}
          | CLIENT-ID: {{ values[8] }}
          {% endfor %}
          {% endfor %}
