- name: Display Kafka consumer group status
  hosts: ingestion-cluster-kafka
  gather_facts: no
  tasks:
    - name: Loop through Kafka consumer groups and check lag status
      shell: /opt/kafka/bin/kafka-consumer-groups.sh --bootstrap-server "localhost:9092" --describe --group "{{ item }}"
      register: consumer_group_output
      loop:
        - "jobmanager"
        - "dev-audit-event-generator-group"
        - "telemetry-group"
        - "prometheus-metrics-consumer"
        - "create-entity-consumer-group"
        - "ml-project-service"
        - "dev-audit-history-indexer-group"
        - "learning-127.0.1.1"
        - "dev-search-indexer-group"
        - "outbound"
        - "dev-enrolment-reconciliation-group"
        - "devsamiksha"
        - "dev-relation-cache-updater-group"
        - "dev-content-publish-group"
        - "dev-qrcode-image-generator-group"
      loop_control:
        label: "{{ item }}"

    - name: Print formatted Kafka lag status
      shell: |
        echo "+------------------------------------------------------------------------------------------------------------------------+"
        echo "| GROUP                             | TOPIC                         | PARTITION | CURRENT-OFFSET | LOG-END-OFFSET | LAG | CONSUMER-ID                            | HOST          | CLIENT-ID          |"
        echo "+------------------------------------------------------------------------------------------------------------------------+"
        for result in {{ consumer_group_output.results }}; do
          echo "$result" | awk 'NR>2 {printf("| %-35s | %-29s | %-10s | %-14s | %-15s | %-4s | %-38s | %-14s | %-14s |\n", $1, $2, $3, $4, $5, $6, $7, $8, $9)}'
        done
        echo "+------------------------------------------------------------------------------------------------------------------------+"
      register: formatted_output

    - debug:
        msg: "{{ formatted_output.stdout }}"
