---
- name: Display Kafka consumer group status
  hosts: ingestion-cluster-kafka
  gather_facts: no
  tasks:
    - name: Loop through Kafka consumer groups and check lag status
      command: /opt/kafka/bin/kafka-consumer-groups.sh --bootstrap-server "localhost:9092" --describe --group "{{ item }}"
      register: consumer_group_output
      loop:
        - "dev-audit-event-generator-group"
        - "telemetry-group"
        - "prometheus-metrics-consumer"
        - "dev-post-publish-processor-group"
        - "ml-project-service"
        - "dev-audit-history-indexer-group"
        - "learning-127.0.1.1"
        - "dev-search-indexer-group"
        - "outbound"
        - "dev-enrolment-reconciliation-group"
        - "devsamiksha"
        - "dev-relation-cache-updater-group"
        - "dev-content-publish-group"
        - "dev-qrcode-image-generator-group"
      loop_control:
        label: "{{ item }}"
    - name: Prepare Kafka consumer group output
      set_fact:
        kafka_groups: |
          {% set results = [] %}
          {% for result in consumer_group_output.results %}
              {% set group_info = {'group_name': result.item, 'members': []} %}
              {% for line in result.stdout_lines[1:] %}
                  {% if line.strip() %}
                      {% set member_info = {'group': group_info['group_name']} %}
                      {% set _ = member_info.update(dict(line.split() | items2dict(keys=['topic', 'partition', 'current_offset', 'log_end_offset', 'lag', 'consumer_id', 'host', 'client_id']))) %}
                      {% set _ = group_info['members'].append(member_info) %}
                  {% endif %}
              {% endfor %}
              {% set _ = results.append(group_info) %}
          {% endfor %}
          {{ results }}

    - name: Render Kafka consumer group output template
      template:
        src: kafka_output_template.j2
        dest: /tmp/kafka_consumer_group_output.txt

    - name: Print Kafka consumer group output file location
      debug:
        msg: "Kafka consumer group output saved to /tmp/kafka_consumer_group_output.txt"
