- name: Display Kafka consumer group status
  hosts: ingestion-cluster-kafka
  gather_facts: no
  tasks:
    - name: Install tabulate Python library
      pip:
        name: tabulate

    - name: Loop through Kafka consumer groups and check lag status
      raw: /opt/kafka/bin/kafka-consumer-groups.sh --bootstrap-server "localhost:9092" --describe --group "{{ item }}"
      register: consumer_group_output
      loop:
        - "dev-audit-event-generator-group"
        - "telemetry-group"
        - "prometheus-metrics-consumer"
        - "dev-post-publish-processor-group"
        - "ml-project-service"
        - "dev-audit-history-indexer-group"
        - "learning-127.0.1.1"
        - "dev-search-indexer-group"
        - "outbound"
        - "dev-enrolment-reconciliation-group"
        - "devsamiksha"
        - "dev-relation-cache-updater-group"
        - "dev-content-publish-group"
        - "dev-qrcode-image-generator-group"
      loop_control:
        label: "{{ item }}"

    - name: Format Kafka consumer group status into table format
      run_once: true
      script: |
        from tabulate import tabulate

        output_data = []  # Define the output_data list here

        headers = ["GROUP", "TOPIC", "PARTITION", "CURRENT-OFFSET", "LOG-END-OFFSET", "LAG", "CONSUMER-ID", "HOST", "CLIENT-ID"]

        for result in consumer_group_output.results:
          for line in result.stdout_lines[2:]:
            row_data = line.split()
            output_data.append(row_data[:9])

        print(tabulate(output_data, headers=headers, tablefmt="pipe"))
