---
- name: Display Kafka consumer group status
  hosts: ingestion-cluster-kafka
  gather_facts: no
  tasks:
    - name: Loop through Kafka consumer groups and check lag status
      command: /opt/kafka/bin/kafka-consumer-groups.sh --bootstrap-server "localhost:9092" --describe --group "{{ item }}"
      register: consumer_group_output
      loop:
        - "dev-audit-event-generator-group"
        - "telemetry-group"
        - "prometheus-metrics-consumer"
        - "dev-post-publish-processor-group"
        - "ml-project-service"
        - "dev-audit-history-indexer-group"
        - "learning-127.0.1.1"
        - "dev-search-indexer-group"
        - "outbound"
        - "dev-enrolment-reconciliation-group"
        - "devsamiksha"
        - "dev-relation-cache-updater-group"
        - "dev-content-publish-group"
        - "dev-qrcode-image-generator-group"
      loop_control:
        label: "{{ item }}"
    - name: Print Kafka lag status for each group
      debug:
        msg: |
          +------------------------------------------------------------------------------------------------------------------------+
          | GROUP | TOPIC | PARTITION | CURRENT-OFFSET | LOG-END-OFFSET | LAG | CONSUMER-ID | HOST | CLIENT-ID |                   |
          +------------------------------------------------------------------------------------------------------------------------+
          {% for result in consumer_group_output.results %}
          {% set output_lines = result.stdout_lines %}
          {%- for line in output_lines[2:] %}
          {%- set values = line.split() %}
          | {{ values[0] }}{{ ' ' * (30 - values[0] | length) }} | {{ values[1] }}{{ ' ' * (40 - values[1] | length) }} | {{ values[2] }}{{ ' ' * (10 - values[2] | length) }} | {{ values[3] }}{{ ' ' * (15 - values[3] | length) }} | {{ values[4] }}{{ ' ' * (15 - values[4] | length) }} | {{ values[5] }}{{ ' ' * (5 - values[5] | length) }} | {{ values[6] }}{{ ' ' * (70 - values[6] | length) }} | {{ values[7] }}{{ ' ' * (15 - values[7] | length) }} | {{ values[8] }}{{ ' ' * (15 - values[8] | length) }} |
          {%- endfor %}
          {%- endfor %}
          +------------------------------------------------------------------------------------------------------------------------+
          {%- if not loop.last %}
          |
          +------------------------------------------------------------------------------------------------------------------------+
          | GROUP | TOPIC | PARTITION | CURRENT-OFFSET | LOG-END-OFFSET | LAG | CONSUMER-ID | HOST | CLIENT-ID |                   |
          +------------------------------------------------------------------------------------------------------------------------+
          {%- endif %}
          {% endfor %}
