- name: Display Kafka consumer group status
  hosts: ingestion-cluster-kafka
  gather_facts: no
  tasks:
    - name: Loop through Kafka consumer groups and check lag status
      command: /opt/kafka/bin/kafka-consumer-groups.sh --bootstrap-server "localhost:9092" --describe --group "{{ item }}"
      register: consumer_group_output
      loop:
        - "dev-audit-event-generator-group"
        - "telemetry-group"
        - "prometheus-metrics-consumer"
        - "dev-post-publish-processor-group"
        - "ml-project-service"
        - "dev-audit-history-indexer-group"
        - "learning-127.0.1.1"
        - "dev-search-indexer-group"
        - "outbound"
        - "dev-enrolment-reconciliation-group"
        - "devsamiksha"
        - "dev-relation-cache-updater-group"
        - "dev-content-publish-group"
        - "dev-qrcode-image-generator-group"
      loop_control:
        label: "{{ item }}"
    - name: Print Kafka lag status for each group
      debug:
        msg: |
          +------------------------------------------------------------------------------------------------------------------------+
          |  GROUP       |       TOPIC       |    PARTITION  |   CURRENT-OFFSET |  LOG-END-OFFSET |   LAG  | CONSUMER-ID | HOST |  CLIENT-ID |
          +------------------------------------------------------------------------------------------------------------------------+
          {%- for result in consumer_group_output.results %}
          {%- set output_lines = result.stdout_lines %}
          {%- set group_name = result.item %}
          +------------------------------------------------------------------------------------------------------------------------+
          |  {{ group_name }} |
          +------------------------------------------------------------------------------------------------------------------------+
          {% for line in output_lines[2:] %}
          | {{ line.split()[0] }} | {{ line.split()[1] }} | {{ line.split()[2] }} | {{ line.split()[3] }} | {{ line.split()[4] }} | {{ line.split()[5] }} | {{ line.split()[6] }} | {{ line.split()[7] }} | {{ line.split()[8] }} |
          {% endfor %}
          +------------------------------------------------------------------------------------------------------------------------+
          {% endfor %}
