- name: Display Kafka consumer group status
  hosts: ingestion-cluster-kafka
  gather_facts: no
  tasks:
    - name: Loop through Kafka consumer groups and check lag status
      command: /opt/kafka/bin/kafka-consumer-groups.sh --bootstrap-server "localhost:9092" --describe --group "{{ item }}"
      register: consumer_group_output
      loop:
        - "dev-audit-event-generator-group"
        - "telemetry-group"
        - "prometheus-metrics-consumer"
        - "dev-post-publish-processor-group"
        - "ml-project-service"
        - "dev-audit-history-indexer-group"
        - "learning-127.0.1.1"
        - "dev-search-indexer-group"
        - "outbound"
        - "dev-enrolment-reconciliation-group"
        - "devsamiksha"
        - "dev-relation-cache-updater-group"
        - "dev-content-publish-group"
        - "dev-qrcode-image-generator-group"
      loop_control:
        loop_var: item

    - name: Convert lag status into table format
      set_fact:
        lag_table: |
          {% for result in consumer_group_output.results %}
          {% set lag = result.stdout | regex_replace('.*LAG\\s+(\\d+)', '\\1') | int %}
          {% set lag_status = "normal (0 to 9)" if lag <= 9 else "high" %}
          {{ result.item + "," + lag_status }}
          {% endfor %}

    - name: Print Kafka lag status table
      debug:
        msg: "{{ lag_table | from_yaml }}"
