- name: Display Kafka consumer group status
  hosts: ingestion-cluster-kafka
  gather_facts: no
  tasks:
    - name: Loop through Kafka consumer groups and check lag status
      command: /opt/kafka/bin/kafka-consumer-groups.sh --bootstrap-server "localhost:9092" --describe --group "{{ item }}"
      register: consumer_group_output
      loop:
        - "dev-audit-event-generator-group"
        - "telemetry-group"
        - "prometheus-metrics-consumer"
        - "dev-post-publish-processor-group"
        - "ml-project-service"
        - "dev-audit-history-indexer-group"
        - "learning-127.0.1.1"
        - "dev-search-indexer-group"
        - "outbound"
        - "dev-enrolment-reconciliation-group"
        - "devsamiksha"
        - "dev-relation-cache-updater-group"
        - "dev-content-publish-group"
        - "dev-qrcode-image-generator-group"
      loop_control:
        label: "{{ item }}"

    - name: Print Kafka lag status for each group
      debug:
        msg: |
          Kafka lag status for group '{{ item.item }}':
          +--------------+-------------------------------+-----------+----------------+---------------+------------+------------+-------------+
          |   GROUP      |   TOPIC                         | PARTITION | CURRENT-OFFSET | LOG-END-OFFSET | LAG        | CONSUMER-ID | CLIENT-ID  |
          +--------------+-------------------------------+-----------+----------------+---------------+------------+------------+-------------+
          | {{ item.stdout | regex_replace('.*GROUP\\s+([^\\s]+).*', '\\1') | default('N/A') | string.center(14) }} | {{ item.stdout | regex_replace('.*TOPIC\\s+([^\\s]+).*', '\\1') | default('N/A') | string.center(30) }} | {{ item.stdout | regex_replace('.*PARTITION\\s+([^\\s]+).*', '\\1') | default('N/A') | string.center(12) }} | {{ item.stdout | regex_replace('.*CURRENT-OFFSET\\s+([^\\s]+).*', '\\1') | default('N/A') | string.center(15) }} | {{ item.stdout | regex_replace('.*LOG-END-OFFSET\\s+([^\\s]+).*', '\\1') | default('N/A') | string.center(15) }} | {{ item.stdout | regex_replace('.*LAG\\s+([^\\s]+).*', '\\1') | default('N/A') | string.center(4) }} | {{ item.stdout | regex_replace('.*CONSUMER-ID\\s+([^\\s]+).*', '\\1') | default('N/A') | string.center(11) }} | {{ item.stdout | regex_replace('.*HOST\\s+([^\\s]+).*', '\\1') | default('N/A') | string.center(6) }} | {{ item.stdout | regex_replace('.*CLIENT-ID\\s+([^\\s]+).*', '\\1') | default('N/A') | string.center(9) }} |
          +--------------+-------------------------------+-----------+----------------+---------------+------------+------------+-------------+
          {% set lag = item.stdout | regex_replace('.*LAG\\s+([^\\s]+).*', '\\1') | int %}
          {% if lag <= 9 %}
          Kafka lag for group '{{ item.item }}' is normal (0 to 9)
          {% else %}
          Kafka lag for group '{{ item.item }}' is high
          {% endif %}
      loop: "{{ consumer_group_output.results }}"
      loop_control:
        label: "{{ item.item }}"
