- name: Display Kafka consumer group status
  hosts: ingestion-cluster-kafka
  gather_facts: no
  tasks:
    - name: Loop through Kafka consumer groups and check lag status
      command: /opt/kafka/bin/kafka-consumer-groups.sh --bootstrap-server "localhost:9092" --group "{{ item }}" --describe
      register: consumer_group_output
      loop:
        - "dev-audit-event-generator-group"
        - "telemetry-group"
        - "prometheus-metrics-consumer"
        - "dev-post-publish-processor-group"
        - "ml-project-service"
        - "dev-audit-history-indexer-group"
        - "learning-127.0.1.1"
        - "dev-search-indexer-group"
        - "outbound"
        - "dev-enrolment-reconciliation-group"
        - "devsamiksha"
        - "dev-relation-cache-updater-group"
        - "dev-content-publish-group"
        - "dev-qrcode-image-generator-group"
      loop_control:
        label: "{{ item }}"
    - name: Print Kafka lag status for each group
      debug:
        msg: |
          {% set header_printed = false %}
          {% for item in consumer_group_output.results %}
            {% if item.stdout.find('No such consumer group') == -1 %}
              {% set consumer_details = item.stdout | regex_replace('.*?GROUP\\s+TOPIC\\s+PARTITION\\s+CURRENT-OFFSET\\s+LOG-END-OFFSET\\s+LAG\\s+CONSUMER-ID\\s+HOST\\s+CLIENT-ID\\s+(.*?)\\n.*', '\\1') %}
              {% set consumer_lines = consumer_details.split('\n') %}
              {% for line in consumer_lines %}
                {% if line %}
                  {% if not header_printed %}
                    +--------+--------+-----------+--------+--------+--------+--------+--------+--------+
                    | GROUP  | TOPIC  | PARTITION | OFFSET |  LOG   |  LAG   | CON-ID |  HOST  | CLIENT |
                    +--------+--------+-----------+--------+--------+--------+--------+--------+--------+
                    {% set header_printed = true %}
                  {% endif %}
                  {% set columns = line.split() %}
                  | {{ columns[0][:6].center(6) }} | {{ columns[1][:6].center(6) }} | {{ columns[2].center(9) }} | {{ columns[3][:6].center(6) }} | {{ columns[4][:6].center(6) }} | {{ columns[5].center(6) }} | {{ columns[6][:6].center(6) }} | {{ columns[7][:6].center(6) }} | {{ columns[8][:6].center(6) }} |
                {% endif %}
              {% endfor %}
            {% endif %}
          {% endfor %}
          +--------+--------+-----------+--------+--------+--------+--------+--------+--------+
      loop: "{{ consumer_group_output.results }}"
      loop_control:
        label: "{{ item.item }}"
