---
- name: SSH to osticket and Print Output
  hosts: "{{ remote }}"
  become: yes
  become_user: root
  vars_files:
    - ['{{inventory_dir}}/secrets.yml', 'secrets/{{env}}.yml']
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
      - name: Execute shell script
        ansible.builtin.command:
          argv:
            - "/home/ubuntu/.script/deployOsTicket.sh" 
            - "{{ branch }}" 
        register: git_pull_output

      - name: Restart Apache
        ansible.builtin.service:
          name: apache2
          state: restarted
        become: yes
        become_user: root
        register: apache2_output
